# Generated by Django 5.1.3 on 2024-11-29 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masyarakat_view', '0001_initial'),
        ('petugas_view', '0005_alter_log_aktivitas_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengaduan',
            name='tanggapan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='petugas_view.tanggapan'),
        ),
    ]
