# Generated by Django 5.1.3 on 2024-11-29 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masyarakat_view', '0002_alter_pengaduan_tanggapan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengaduan',
            name='tanggapan',
        ),
    ]
