# Generated by Django 5.1.3 on 2024-11-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masyarakat_view', '0003_remove_pengaduan_tanggapan'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenis_laporan',
            name='foto',
            field=models.ImageField(default='', upload_to='gambar_jenis_laporan/'),
            preserve_default=False,
        ),
    ]
