# Generated by Django 5.1.3 on 2024-11-29 10:43

import ckeditor.fields
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dinas_view', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Petugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=35)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('level', models.CharField(choices=[('admin', 'Admin'), ('petugas', 'Petugas')], max_length=10)),
                ('telp', models.IntegerField(max_length=13)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('dinas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinas_view.dinas')),
            ],
            options={
                'verbose_name': 'Petugas',
                'verbose_name_plural': 'Petugas',
            },
        ),
        migrations.CreateModel(
            name='Log_Aktivitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktifitas', models.DateField(auto_now=True)),
                ('tanggal', models.DateTimeField(default=datetime.datetime(2024, 11, 29, 10, 43, 1, 478106, tzinfo=datetime.timezone.utc))),
                ('petugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Aktifitas',
                'verbose_name_plural': 'Log Aktifitas',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='Tanggapan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_tanggapan', models.DateTimeField(auto_now_add=True)),
                ('tanggapan', ckeditor.fields.RichTextField()),
                ('status', models.CharField(choices=[('0', 'Belum Terjawab'), ('desposisi', 'Desposisi'), ('proses', 'Proses'), ('selesai', 'Selesai'), ('tolak', 'Tolaks')], default='0', max_length=9)),
                ('petugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tanggapan',
                'verbose_name_plural': 'Tanggapan',
            },
        ),
    ]
