# Generated by Django 5.1.3 on 2024-11-29 10:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinas_view', '0001_initial'),
        ('petugas_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_aktivitas',
            name='tanggal',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 29, 10, 44, 26, 962232, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='petugas',
            name='dinas',
            field=models.ForeignKey(default='Departemen Iserk', on_delete=django.db.models.deletion.CASCADE, to='dinas_view.dinas'),
        ),
    ]
