# Generated by Django 5.1.3 on 2024-11-29 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petugas_view', '0004_alter_log_aktivitas_tanggal_alter_petugas_dinas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_aktivitas',
            name='tanggal',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 29, 10, 48, 40, 664235, tzinfo=datetime.timezone.utc)),
        ),
    ]
