# Generated by Django 5.1.3 on 2024-11-29 10:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masyarakat_view', '0003_remove_pengaduan_tanggapan'),
        ('petugas_view', '0005_alter_log_aktivitas_tanggal'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanggapan',
            name='pengaduan',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='masyarakat_view.pengaduan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log_aktivitas',
            name='tanggal',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 29, 10, 57, 28, 309037, tzinfo=datetime.timezone.utc)),
        ),
    ]
