# Generated by Django 5.1.3 on 2024-11-30 09:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinas_view', '0001_initial'),
        ('petugas_view', '0006_tanggapan_pengaduan_alter_log_aktivitas_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_aktivitas',
            name='tanggal',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 30, 9, 34, 29, 32776, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='petugas',
            name='dinas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinas_view.dinas'),
        ),
        migrations.AlterField(
            model_name='petugas',
            name='level',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('petugas', 'Petugas')], default='petugas', max_length=10, null=True),
        ),
    ]
