# Generated by Django 5.1.3 on 2024-11-30 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petugas_view', '0007_alter_log_aktivitas_tanggal_alter_petugas_dinas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_aktivitas',
            name='tanggal',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 30, 9, 35, 11, 286433, tzinfo=datetime.timezone.utc)),
        ),
    ]
