# Generated by Django 5.1.3 on 2024-11-30 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petugas_view', '0014_alter_log_aktivitas_tanggal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_aktivitas',
            name='aktifitas',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='log_aktivitas',
            name='tanggal',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 30, 10, 13, 36, 715067, tzinfo=datetime.timezone.utc)),
        ),
    ]
