# Generated by Django 5.1.3 on 2024-11-30 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petugas_view', '0015_alter_log_aktivitas_aktifitas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_aktivitas',
            name='tanggal',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 30, 18, 33, 38, 805148, tzinfo=datetime.timezone.utc)),
        ),
    ]
