# Generated by Django 5.1.3 on 2024-11-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=35)),
                ('deskripsi', models.TextField()),
                ('kepala', models.CharField(max_length=35)),
                ('telp', models.CharField(max_length=13)),
            ],
            options={
                'verbose_name': 'Dinas',
                'verbose_name_plural': 'Dinas',
            },
        ),
    ]
