# Generated by Django 5.1.3 on 2024-11-30 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinas_view', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinas',
            name='deskripsi',
        ),
        migrations.RemoveField(
            model_name='dinas',
            name='kepala',
        ),
    ]
